Added missing dependency on sync-request
Without the `sync-request` module mocha would fail with the following error message due to a missing dependency

```
internal/modules/cjs/loader.js:638
throw err;
^
Error: Cannot find module 'sync-request'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
at Function.Module._load (internal/modules/cjs/loader.js:562:25)
at Module.require (internal/modules/cjs/loader.js:692:17)
at require (internal/modules/cjs/helpers.js:25:18)
```

In order to be able to run the tests successfully you need to ensure that sync-request is installed, so I've added it as a requirement when installing Mocha

This results in being able to follow the guide step-by-step and apply the commands locally without error